/**
 * Symmetric secret box. Used to encrypt plugin API keys etc. at rest
 * in the `secrets` table.
 *
 * Algorithm: AES-256-GCM. Authenticated encryption — one primitive
 * gives confidentiality + integrity, no separate HMAC step. Picked
 * over Fernet (the original spec suggestion) because GCM is in
 * node:crypto natively, no extra dep, and the ciphertext format we
 * pick is dead-simple:
 *
 *     [nonce 12B] [auth tag 16B] [ciphertext ...]   (all one BLOB)
 *
 * Key handling:
 *   - Read base64 32-byte key from `SMITH_SECRET_KEY` env var
 *   - If missing on first call: generate one, write it back to .env,
 *     warn loudly that the operator must back it up. Losing the key
 *     means every stored secret is unrecoverable; Smith will keep
 *     working but each affected plugin will need its secret re-entered.
 *
 * Why auto-generate vs require operator-provided: lower friction for
 * single-user dev installs (the most common Smith deployment). Ops
 * can still pre-set the env var for prod / multi-machine setups.
 */
import {
  createCipheriv,
  createDecipheriv,
  randomBytes,
} from "node:crypto";
import { appendFileSync, existsSync } from "node:fs";
import { resolve as resolvePath } from "node:path";

const ENV_VAR = "SMITH_SECRET_KEY";
const KEY_BYTES = 32;     // AES-256
const NONCE_BYTES = 12;   // GCM standard
const TAG_BYTES = 16;     // GCM standard

let _key: Buffer | null = null;

function ensureKey(): Buffer {
  if (_key) return _key;
  let raw = process.env[ENV_VAR]?.trim();
  if (!raw) {
    raw = generateAndPersistKey();
  }
  const buf = Buffer.from(raw, "base64");
  if (buf.length !== KEY_BYTES) {
    throw new Error(
      `${ENV_VAR} must decode to ${KEY_BYTES} bytes (base64); got ${buf.length}. ` +
      `Generate a fresh one with: node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"`,
    );
  }
  _key = buf;
  return buf;
}

function generateAndPersistKey(): string {
  const generated = randomBytes(KEY_BYTES).toString("base64");
  const envPath = resolvePath(process.cwd(), ".env");
  const block = existsSync(envPath) ? "\n" : "";
  appendFileSync(
    envPath,
    `${block}# Auto-generated by smith/db/secrets.ts.\n` +
    `# Encrypts plugin secrets stored in .data/smith.db.\n` +
    `# BACK THIS UP — losing it = every stored secret becomes unrecoverable\n` +
    `# (you'll have to re-enter each plugin's API key).\n` +
    `${ENV_VAR}=${generated}\n`,
  );
  process.env[ENV_VAR] = generated;
  console.warn(
    `[smith.secrets] generated ${ENV_VAR} and appended to .env. ` +
    `BACK IT UP — it encrypts plugin secrets and isn't recoverable.`,
  );
  return generated;
}

/** Encrypt a UTF-8 string. Returns the BLOB to store in
 *  secrets.ciphertext (nonce || tag || ciphertext). */
export function encryptSecret(plaintext: string): Buffer {
  const key = ensureKey();
  const nonce = randomBytes(NONCE_BYTES);
  const cipher = createCipheriv("aes-256-gcm", key, nonce);
  const ct = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return Buffer.concat([nonce, tag, ct]);
}

/** Decrypt a BLOB written by `encryptSecret`. Throws on auth tag
 *  mismatch (tampered or wrong key). */
export function decryptSecret(blob: Buffer): string {
  if (blob.length < NONCE_BYTES + TAG_BYTES) {
    throw new Error(`ciphertext blob too short (${blob.length} bytes)`);
  }
  const key = ensureKey();
  const nonce = blob.subarray(0, NONCE_BYTES);
  const tag = blob.subarray(NONCE_BYTES, NONCE_BYTES + TAG_BYTES);
  const ct = blob.subarray(NONCE_BYTES + TAG_BYTES);
  const decipher = createDecipheriv("aes-256-gcm", key, nonce);
  decipher.setAuthTag(tag);
  return Buffer.concat([decipher.update(ct), decipher.final()]).toString("utf8");
}
